name: WorldProtect
version: 1.0
api-version: 1.20
main: net.vertrauterdavid.worldprotect.WorldProtect
author: VertrauterDavid
website: https://vertrauterdavid.net/ & https://github.com/vertrauterdavid/