name: WorldProtect
version: 1.0
api-version: 1.20
main: net.vertrauterdavid.worldprotect.WorldProtect
author: VertrauterDavid & JavaMio
website: https://vertrauterdavid.net/ & https://github.com/vertrauterdavid/
folia-supported: true